# render engine config


# memory pool options
memory:  # size in GB
    main_memory_size: 2


# image options
image:
    write_image: false          # true: write image to path = "/tmp", false: don't write.
