schedule:
    ip_addr: 127.0.0.1
    master:
        port: 21000

    worker:
        num: 1
        stage:
            build_task_context_parallelism: 8
            fetch_meta_parallelism: 8
            compile_parallelism: 8
            fetch_data_parallelism: 2
            compute_parallelism: 1
            output_parallelism: 1

engine_config:
    bitcode_lib: @bitcode_lib@
    agg:
        hash_factor: 0.5
        bucket_time_out: 100

storage_config:
    db_path: @db_path@
    row_per_fragment: 10000000
    text_column_keygen: tree    #keygen method for string, optional: tree    , hash, sequence
    text_group_policy: column   #auto assign group name for undefined tex    t column, optional: database, table ,column
    text_group:
        group_1:            # group name
            keygen: hash        # group keygen, optional: tree, hash
            columns:
                - s.0           # group columns, table_name.column_index. Wildcard is accepted (using std::regex).
                - t.0           # If ‘tree’ is selected, only one column is accepted.

bulletin:
    ip_addr: 127.0.0.1
    port: 2379

chewie:
    data_client:
        ip_addr: 0.0.0.0
        port: 50023
      
log:
    path: /tmp
    level: 1                    # optional: trace = 0, debug = 1, info = 2, warn = 3, error = 4, critical = 5, off = 6
    rotating: yes               # yes means rotated log, no means non-rotated log;
    rotating_size_limit: 64     # 64 MB, valid when rotating is yes
    rotating_number_limit: 10   # valid when rotating is yes
          
